### ISSUE TITLE
facing issue while training

### ISSUE THREAD

**Issue by kunalpurkayastha** [huyquoctrinh/MetaPolyp-CBMS2023#5]
Hello there,
I am facing the below error while I try to train with the given dataset only

Traceback (most recent call last):
File "train.py", line 35, in <module>
model = build_model(img_size)
File "/home/kunal/Documents/MetaPolyp-CBMS2023/model.py", line 21, in build_model
upscale_feature = decode(x, scale = 4, filters = x.shape[channel_axis])
File "/home/kunal/Documents/MetaPolyp-CBMS2023/layers/upsampling.py", line 14, in decode
x1 = tf.keras.layers.Conv2D(filters, (1, 1), activation=activation, use_bias=False,
File "/home/kunal/.conda/envs/scorpio/lib/python3.8/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
raise e.with_traceback(filtered_tb) from None
File "/home/kunal/.conda/envs/scorpio/lib/python3.8/site-packages/keras/src/engine/input_spec.py", line 253,in assert_input_compatibility
raise ValueError(
ValueError: Input 0 of layer "conv2d" is incompatible with the layer: expected min_ndim=4, found ndim=3. Full shape received: (None, 64, 512)

please help me to fix this

**Comment by huyquoctrinh** [comment]
Hi @kunalpurkayastha , thank you so much for this issue. This issue can be fixed via the installation `keras-cv-attention-models==1.3.9` package, I updated in the  `requirements.txt ` file. I hope you can fix it.

**Comment by huyquoctrinh** [comment]
Hi everyone, this issue solution is updated in the README, you guys can follow in that, I will close this issue
